sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    ‐ $GOPATH/bin/hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: KennaNing/KennaNing.github.io
   # fqdn: <custom-domain-if-needed>
    target_branch: master
    email: fangning0110@outlook.com
    name: KennaNing
