baseURL = "http://KennaNing.github.io"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-minos"
paginate = 10
[params]
    smartToc = true
    googleAnalytics = "UA-123-45"
    katex = true
